language: node_js

node_js:
  - "lts/*"

before_install:

install:
  - npm install
  # - npm i --save-dev https://github.com/ebidel/lighthouse-ci

before_script:

script:
  - npm run eslint
  - npm run stylelint
  # - bash ./travis/deploy-to-test-server.sh
  # - npm run lh -- --pwa=60 --perf=60 --seo=60 --a11y=60 --bp=60  http://eb042655.ngrok.io/


after_success:

before_deploy:
  
deploy:
  # - bash ./travis/deploy.sh

after_deploy:

after_script:
